### ISSUE TITLE
Fix Appveyor testing

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/ufodiff#17]
There is a bug on the setuptools pull on the Appveyor side that is leading to test failures.  This does not appear to be an issue with the ufodiff software or any of its dependencies.  Appears to be part of Appveyor install process for testing.  

Tests still passing on Travis/Linux.

Appveyor stdout/stderr message:

```
Build started
ECHO %TOXENV%
py27
ls C:\Python*
    Directory: C:\
Mode                LastWriteTime         Length Name                                                                                                                                                                                
----                -------------         ------ ----                                                                                                                                                                                
d-----        4/20/2016   2:59 AM                Python26                                                                                                                                                                            
d-----        4/20/2016   2:59 AM                Python26-x64                                                                                                                                                                        
d-----       12/28/2016   9:47 PM                Python27                                                                                                                                                                            
d-----       12/28/2016   9:47 PM                Python27-x64                                                                                                                                                                        
d-----        4/20/2016   2:59 AM                Python33                                                                                                                                                                            
d-----        4/20/2016   2:59 AM                Python33-x64                                                                                                                                                                        
d-----         8/5/2016   2:35 AM                Python34                                                                                                                                                                            
d-----         8/5/2016   2:35 AM                Python34-x64                                                                                                                                                                        
d-----        2/19/2017   7:23 PM                Python35                                                                                                                                                                            
d-----        2/19/2017   7:24 PM                Python35-x64                                                                                                                                                                        
d-----        4/22/2017   7:59 PM                Python36                                                                                                                                                                            
d-----        4/22/2017   8:00 PM                Python36-x64                                                                                                                                                                        
git clone -q https://github.com/source-foundry/ufodiff.git C:\projects\ufodiff
git fetch -q origin +refs/pull/16/merge:
git checkout -qf FETCH_HEAD
Running Install scripts
Invoke-WebRequest "https://bootstrap.pypa.io/ez_setup.py" -OutFile "c:\\ez_setup.py"
Invoke-WebRequest "https://bootstrap.pypa.io/get-pip.py" -OutFile "c:\\get-pip.py"
c:\python27\python c:\ez_setup.py
ez_setup.py is deprecated and when using it setuptools will be pinned to 33.1.1 since it's the last version that supports setuptools self upgrade/installation, check https://github.com/pypa/setuptools/issues/581 for more info; use pip to install setuptools
Downloading https://pypi.io/packages/source/s/setuptools/setuptools-33.1.1.zip
Exception calling "DownloadFile" with "2" argument(s): "The request was 
aborted: Could not create SSL/TLS secure channel."
At line:1 char:106
+ ... redentials; (new-object System.Net.WebClient).DownloadFile("https://p ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
 
Traceback (most recent call last):
  File "c:\ez_setup.py", line 414, in <module>
    sys.exit(main())
  File "c:\ez_setup.py", line 410, in main
    archive = download_setuptools(**_download_args(options))
  File "c:\ez_setup.py", line 355, in download_setuptools
    downloader(url, saveto)
  File "c:\ez_setup.py", line 256, in download_file_powershell
    _clean_check(cmd, target)
  File "c:\ez_setup.py", line 230, in _clean_check
    subprocess.check_call(cmd)
  File "c:\python27\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['powershell', '-Command', '[System.Net.WebRequest]::DefaultWebProxy.Credentials = [System.Net.CredentialCache]::DefaultCredentials; (new-object System.Net.WebClient).DownloadFile("https://pypi.io/packages/source/s/setuptools/setuptools-33.1.1.zip", "C:\\projects\\ufodiff\\setuptools-33.1.1.zip")']' returned non-zero exit status 1
Command exited with code 1
```

See #16 PR

**Comment by anthrotype** [comment]
the error message says:

> ez_setup.py is deprecated

exactly, you don't need to use the old setuptools bootstrapping script. The way to install setuptools is via pip. When you install pip (via get-pip.py) you automatically also get setuptools (which is a pip dependency).

By the way, pip (and setuptools) are preinstalled on all python distributions, including appveyors. If you just want to ensure they are up to date simply do `python -m pip install --upgrade setuptools` and `python -m pip install --upgrade pip`.

**Comment by chrissimpkins** [comment]
Sadly, the appveyor settings were copy/paste from other Python projects.  Let me dig into the Powershell commands and see if I can figure out where I am causing problems.  Don't have experience on the Win side...

**Comment by anthrotype** [comment]
although that is just a deprecation _warning_, not the root cause of the error.
The error that makes it abort is "Could not create SSL/TLS secure channel", and happens on Python 3.3 which also reached end of life some time ago. I'd just drop 2.6 and 3.3, they are too old to bother.

**Comment by chrissimpkins** [comment]
Here is file:

```
build: false
environment:
  matrix:
    - TOXENV: py27
    - TOXENV: py34
    - TOXENV: py35
    - TOXENV: py36
platform:
  - x86
  - x64
init:
  - "ECHO %TOXENV%"
  - ps: "ls C:\\Python*"
install:
  - ps: Invoke-WebRequest "https://bootstrap.pypa.io/ez_setup.py" -OutFile "c:\\ez_setup.py"
  - ps: Invoke-WebRequest "https://bootstrap.pypa.io/get-pip.py" -OutFile "c:\\get-pip.py"
  - "c:\\python27\\python c:\\ez_setup.py"
  - "c:\\python27\\python c:\\get-pip.py"
  - "c:\\python27\\Scripts\\pip install tox"
test_script:
  - "git clean -f -d -x"
  - "c:\\python27\\Scripts\\tox --version"
  - "c:\\python27\\Scripts\\pip --version"
- "c:\\python27\\Scripts\\tox"
```

We shouldn't be testing 2.6 or 3.3 based upon those settings.  I will try to pull out all of the bootstrapping code and all ez_setup.py commands to see if that works.

Thanks!

**Comment by anthrotype** [comment]
have a look at fonttools appveyor.yml file for a working example.

**Comment by chrissimpkins** [comment]
will do! ty

**Comment by anthrotype** [comment]
I know, it's tricky to get it working the first time, especially if you don't have direct access to a windows machine where you can play with the command prompt.

**Comment by chrissimpkins** [comment]
I've used these scripts for well over a year.  Something must have changed in the last couple of weeks because Appveyor builds / tests worked fine with the current settings.  Benefit of creating cron jobs / automated dependency PR's for your testing I suppose :)

**Comment by anthrotype** [comment]
sorry, what I said early on about python 3.3 is bullshit... _33_ was the setuptools version that the old ez_setup.py is pinned to. 😊 
yeah, it's probably something that changed upstream. Anyway, just use pip to upgrade setuptools.

**Comment by anthrotype** [comment]
your appveyor.yml is correct, except for the unnecessary calls to ez_setup.py and get-pip.py. Both pip and setuptools are already there on Appveyor's pythons. You could upgrade them, but you don't really need to. `pip install tox` should just work if you remove those two lines.

**Comment by chrissimpkins** [comment]
:+1: tyvm! will give it a try tonight

**Comment by chrissimpkins** [comment]
worked! thanks much Cosimo.  I really appreciate your help
